<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class BienTheSanPhamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $startDate  = Carbon::create(2024, 10, 1);
        $endDate    = Carbon::create(2024, 12, 1);
        DB::table('bien_the_san_phams')->delete();
        DB::table('bien_the_san_phams')->truncate();
        DB::table('bien_the_san_phams')->insert([
            [
                'id_san_pham'   => 1,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Đen',
                'chat_lieu'     => 'Cotton',
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 1,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Đen',
                'chat_lieu'     => 'Cotton',
                'so_luong_ton'  => 15,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 1,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Đen',
                'chat_lieu'     => 'Cotton',
                'so_luong_ton'  => 5,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 2,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Xanh dương',
                'chat_lieu'     => 'Denim',
                'so_luong_ton'  => 8,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 2,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Xanh dương',
                'chat_lieu'     => 'Denim',
                'so_luong_ton'  => 12,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 2,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Xanh dương',
                'chat_lieu'     => 'Denim',
                'so_luong_ton'  => 6,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 3,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Trắng',
                'chat_lieu'     => 'Polyester',
                'so_luong_ton'  => 20,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 3,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Trắng',
                'chat_lieu'     => 'Polyester',
                'so_luong_ton'  => 18,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 3,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Trắng',
                'chat_lieu'     => 'Polyester',
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 4,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Đỏ',
                'chat_lieu'     => 'Lụa',
                'so_luong_ton'  => 7,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 4,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Đỏ',
                'chat_lieu'     => 'Lụa',
                'so_luong_ton'  => 5,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 4,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Đỏ',
                'chat_lieu'     => 'Lụa',
                'so_luong_ton'  => 3,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 5,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Xám',
                'chat_lieu'     => 'Len',
                'so_luong_ton'  => 11,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 5,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Xám',
                'chat_lieu'     => 'Len',
                'so_luong_ton'  => 14,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 5,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Xám',
                'chat_lieu'     => 'Len',
                'so_luong_ton'  => 9,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 6,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Hồng',
                'chat_lieu'     => 'Vải thun',
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 6,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Hồng',
                'chat_lieu'     => 'Vải thun',
                'so_luong_ton'  => 12,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 6,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Hồng',
                'chat_lieu'     => 'Vải thun',
                'so_luong_ton'  => 8,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 7,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Be',
                'chat_lieu'     => 'Vải linen',
                'so_luong_ton'  => 9,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 7,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Be',
                'chat_lieu'     => 'Vải linen',
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 8,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Vàng',
                'chat_lieu'     => 'Lụa',
                'so_luong_ton'  => 15,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 8,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Vàng',
                'chat_lieu'     => 'Lụa',
                'so_luong_ton'  => 20,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 8,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Vàng',
                'chat_lieu'     => 'Lụa',
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 9,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Xanh lá cây',
                'chat_lieu'     => 'Bông',
                'so_luong_ton'  => 18,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 9,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Xanh lá cây',
                'chat_lieu'     => 'Bông',
                'so_luong_ton'  => 25,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 9,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Xanh lá cây',
                'chat_lieu'     => 'Bông',
                'so_luong_ton'  => 30,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 10,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Hồng nhạt',
                'chat_lieu'     => 'Vải thô',
                'so_luong_ton'  => 12,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 10,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Hồng nhạt',
                'chat_lieu'     => 'Vải thô',
                'so_luong_ton'  => 14,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 10,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Hồng nhạt',
                'chat_lieu'     => 'Vải thô',
                'so_luong_ton'  => 8,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        ]);
    }
}
