<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class BienTheSanPhamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $startDate  = Carbon::create(2024, 10, 1);
        $endDate    = Carbon::create(2024, 12, 1);
        DB::table('bien_the_san_phams')->delete();
        DB::table('bien_the_san_phams')->truncate();
        DB::table('bien_the_san_phams')->insert([
            [
                'id_san_pham'   => 1,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Đen',
                'chat_lieu'     => 'Cotton',
                'gia_nhap'      => 200000,
                'gia_ban'       => 500000,
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 1,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Đen',
                'chat_lieu'     => 'Cotton',
                'gia_nhap'      => 210000,
                'gia_ban'       => 520000,
                'so_luong_ton'  => 15,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 1,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Đen',
                'chat_lieu'     => 'Cotton',
                'gia_nhap'      => 220000,
                'gia_ban'       => 540000,
                'so_luong_ton'  => 5,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 2,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Xanh dương',
                'chat_lieu'     => 'Denim',
                'gia_nhap'      => 300000,
                'gia_ban'       => 750000,
                'so_luong_ton'  => 8,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 2,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Xanh dương',
                'chat_lieu'     => 'Denim',
                'gia_nhap'      => 310000,
                'gia_ban'       => 770000,
                'so_luong_ton'  => 12,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 2,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Xanh dương',
                'chat_lieu'     => 'Denim',
                'gia_nhap'      => 320000,
                'gia_ban'       => 790000,
                'so_luong_ton'  => 6,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 3,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Trắng',
                'chat_lieu'     => 'Polyester',
                'gia_nhap'      => 150000,
                'gia_ban'       => 450000,
                'so_luong_ton'  => 20,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 3,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Trắng',
                'chat_lieu'     => 'Polyester',
                'gia_nhap'      => 160000,
                'gia_ban'       => 460000,
                'so_luong_ton'  => 18,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 3,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Trắng',
                'chat_lieu'     => 'Polyester',
                'gia_nhap'      => 170000,
                'gia_ban'       => 470000,
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 4,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Đỏ',
                'chat_lieu'     => 'Lụa',
                'gia_nhap'      => 600000,
                'gia_ban'       => 1200000,
                'so_luong_ton'  => 7,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 4,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Đỏ',
                'chat_lieu'     => 'Lụa',
                'gia_nhap'      => 650000,
                'gia_ban'       => 1250000,
                'so_luong_ton'  => 5,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 4,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Đỏ',
                'chat_lieu'     => 'Lụa',
                'gia_nhap'      => 700000,
                'gia_ban'       => 1300000,
                'so_luong_ton'  => 3,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 5,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Xám',
                'chat_lieu'     => 'Len',
                'gia_nhap'      => 400000,
                'gia_ban'       => 850000,
                'so_luong_ton'  => 11,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 5,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Xám',
                'chat_lieu'     => 'Len',
                'gia_nhap'      => 420000,
                'gia_ban'       => 880000,
                'so_luong_ton'  => 14,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 5,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Xám',
                'chat_lieu'     => 'Len',
                'gia_nhap'      => 440000,
                'gia_ban'       => 900000,
                'so_luong_ton'  => 9,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 6,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Hồng',
                'chat_lieu'     => 'Vải thun',
                'gia_nhap'      => 250000,
                'gia_ban'       => 600000,
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 6,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Hồng',
                'chat_lieu'     => 'Vải thun',
                'gia_nhap'      => 270000,
                'gia_ban'       => 620000,
                'so_luong_ton'  => 12,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 6,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Hồng',
                'chat_lieu'     => 'Vải thun',
                'gia_nhap'      => 290000,
                'gia_ban'       => 650000,
                'so_luong_ton'  => 8,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 7,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Be',
                'chat_lieu'     => 'Vải linen',
                'gia_nhap'      => 450000,
                'gia_ban'       => 900000,
                'so_luong_ton'  => 9,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 7,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Be',
                'chat_lieu'     => 'Vải linen',
                'gia_nhap'      => 470000,
                'gia_ban'       => 920000,
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 8,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Vàng',
                'chat_lieu'     => 'Lụa',
                'gia_nhap'      => 550000,
                'gia_ban'       => 1100000,
                'so_luong_ton'  => 15,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 8,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Vàng',
                'chat_lieu'     => 'Lụa',
                'gia_nhap'      => 570000,
                'gia_ban'       => 1150000,
                'so_luong_ton'  => 20,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 8,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Vàng',
                'chat_lieu'     => 'Lụa',
                'gia_nhap'      => 600000,
                'gia_ban'       => 1200000,
                'so_luong_ton'  => 10,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 9,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Xanh lá cây',
                'chat_lieu'     => 'Bông',
                'gia_nhap'      => 250000,
                'gia_ban'       => 600000,
                'so_luong_ton'  => 18,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 9,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Xanh lá cây',
                'chat_lieu'     => 'Bông',
                'gia_nhap'      => 260000,
                'gia_ban'       => 620000,
                'so_luong_ton'  => 25,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 9,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Xanh lá cây',
                'chat_lieu'     => 'Bông',
                'gia_nhap'      => 270000,
                'gia_ban'       => 640000,
                'so_luong_ton'  => 30,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 10,
                'kich_thuoc'    => 'S',
                'mau_sac'       => 'Hồng nhạt',
                'chat_lieu'     => 'Vải thô',
                'gia_nhap'      => 180000,
                'gia_ban'       => 450000,
                'so_luong_ton'  => 12,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 10,
                'kich_thuoc'    => 'M',
                'mau_sac'       => 'Hồng nhạt',
                'chat_lieu'     => 'Vải thô',
                'gia_nhap'      => 190000,
                'gia_ban'       => 460000,
                'so_luong_ton'  => 14,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_san_pham'   => 10,
                'kich_thuoc'    => 'L',
                'mau_sac'       => 'Hồng nhạt',
                'chat_lieu'     => 'Vải thô',
                'gia_nhap'      => 200000,
                'gia_ban'       => 480000,
                'so_luong_ton'  => 8,
                'tinh_trang'    => '1',
                'created_at'    => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        ]);
    }
}
