<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhuongXaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('phuong_xas')->delete();
        DB::table('phuong_xas')->truncate();

        DB::table('phuong_xas')->insert([
            // Phường xã của Châu Đốc (id_quan_huyen = 1)
            ['ten_phuong_xa' => 'Phường Châu Phú A', 'id_quan_huyen' => 1],
            ['ten_phuong_xa' => 'Phường Châu Phú B', 'id_quan_huyen' => 1],
            ['ten_phuong_xa' => 'Phường Vĩnh Mỹ', 'id_quan_huyen' => 1],
            ['ten_phuong_xa' => 'Phường Núi Sam', 'id_quan_huyen' => 1],
            ['ten_phuong_xa' => 'Xã Vĩnh Tế', 'id_quan_huyen' => 1],
            ['ten_phuong_xa' => 'Xã Vĩnh Châu', 'id_quan_huyen' => 1],


    // Phường xã của Châu Phú (id_quan_huyen = 2)
    ['ten_phuong_xa' => 'Thị trấn Cái Dầu', 'id_quan_huyen' => 2],
    ['ten_phuong_xa' => 'Xã Khánh Hòa', 'id_quan_huyen' => 2],
    ['ten_phuong_xa' => 'Xã Mỹ Đức', 'id_quan_huyen' => 2],
    ['ten_phuong_xa' => 'Xã Mỹ Phú', 'id_quan_huyen' => 2],
    ['ten_phuong_xa' => 'Xã Ô Long Vĩ', 'id_quan_huyen' => 2],
    ['ten_phuong_xa' => 'Xã Thạnh Mỹ Tây', 'id_quan_huyen' => 2],
    ['ten_phuong_xa' => 'Xã Vĩnh Thạnh Trung', 'id_quan_huyen' => 2],
    ['ten_phuong_xa' => 'Xã Bình Chánh', 'id_quan_huyen' => 2],
    ['ten_phuong_xa' => 'Xã Bình Long', 'id_quan_huyen' => 2],
    ['ten_phuong_xa' => 'Xã Bình Mỹ', 'id_quan_huyen' => 2],

    ['ten_phuong_xa' => 'Phường Mỹ Bình', 'id_quan_huyen' => 3],
['ten_phuong_xa' => 'Phường Mỹ Long', 'id_quan_huyen' => 3],
['ten_phuong_xa' => 'Phường Mỹ Xuyên', 'id_quan_huyen' => 3],
['ten_phuong_xa' => 'Phường Mỹ Thới', 'id_quan_huyen' => 3],
['ten_phuong_xa' => 'Phường Mỹ Phước', 'id_quan_huyen' => 3],
['ten_phuong_xa' => 'Phường Mỹ Quý', 'id_quan_huyen' => 3],
['ten_phuong_xa' => 'Xã Mỹ Hòa Hưng', 'id_quan_huyen' => 3],

['ten_phuong_xa' => 'Phường Long Thạnh', 'id_quan_huyen' => 4],
['ten_phuong_xa' => 'Phường Long Hưng', 'id_quan_huyen' => 4],
['ten_phuong_xa' => 'Phường Long Châu', 'id_quan_huyen' => 4],
['ten_phuong_xa' => 'Xã Châu Phong', 'id_quan_huyen' => 4],
['ten_phuong_xa' => 'Xã Phú Lộc', 'id_quan_huyen' => 4],
['ten_phuong_xa' => 'Xã Tân An', 'id_quan_huyen' => 4],
['ten_phuong_xa' => 'Xã Tân Thạnh', 'id_quan_huyen' => 4],
['ten_phuong_xa' => 'Xã Vĩnh Xương', 'id_quan_huyen' => 4],
['ten_phuong_xa' => 'Xã Vĩnh Hòa', 'id_quan_huyen' => 4],


['ten_phuong_xa' => 'Thị trấn An Phú', 'id_quan_huyen' => 5],
['ten_phuong_xa' => 'Xã Khánh An', 'id_quan_huyen' => 5],
['ten_phuong_xa' => 'Xã Khánh Bình', 'id_quan_huyen' => 5],
['ten_phuong_xa' => 'Xã Quốc Thái', 'id_quan_huyen' => 5],
['ten_phuong_xa' => 'Xã Nhơn Hội', 'id_quan_huyen' => 5],
['ten_phuong_xa' => 'Xã Phú Hữu', 'id_quan_huyen' => 5],
['ten_phuong_xa' => 'Xã Vĩnh Hội Đông', 'id_quan_huyen' => 5],
['ten_phuong_xa' => 'Xã Vĩnh Trường', 'id_quan_huyen' => 5],
['ten_phuong_xa' => 'Xã Đa Phước', 'id_quan_huyen' => 5],

['ten_phuong_xa' => 'Phường 1', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Phường 2', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Phường 3', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Phường 4', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Phường 5', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Phường Nguyễn An Ninh', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Phường Thắng Nhì', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Phường Thắng Tam', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Phường Rạch Dừa', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Phường Thắng Nhất', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Xã Long Sơn', 'id_quan_huyen' => 6],
['ten_phuong_xa' => 'Thị trấn Long Điền', 'id_quan_huyen' => 7],
['ten_phuong_xa' => 'Thị trấn Long Hải', 'id_quan_huyen' => 7],
['ten_phuong_xa' => 'Xã An Ngãi', 'id_quan_huyen' => 7],
['ten_phuong_xa' => 'Xã Tam Phước', 'id_quan_huyen' => 7],
['ten_phuong_xa' => 'Xã An Nhứt', 'id_quan_huyen' => 7],
['ten_phuong_xa' => 'Xã Phước Hưng', 'id_quan_huyen' => 7],
['ten_phuong_xa' => 'Xã Phước Tỉnh', 'id_quan_huyen' => 7],
['ten_phuong_xa' => 'Phường Phú Mỹ', 'id_quan_huyen' => 8],
['ten_phuong_xa' => 'Phường Mỹ Xuân', 'id_quan_huyen' => 8],
['ten_phuong_xa' => 'Phường Hắc Dịch', 'id_quan_huyen' => 8],
['ten_phuong_xa' => 'Xã Tân Hòa', 'id_quan_huyen' => 8],
['ten_phuong_xa' => 'Xã Tân Hải', 'id_quan_huyen' => 8],
['ten_phuong_xa' => 'Xã Tóc Tiên', 'id_quan_huyen' => 8],
['ten_phuong_xa' => 'Xã Châu Pha', 'id_quan_huyen' => 8],
['ten_phuong_xa' => 'Thị trấn Ngãi Giao', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Suối Nghệ', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Bình Ba', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Bình Giã', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Bình Trung', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Đá Bạc', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Kim Long', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Nghĩa Thành', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Quảng Thành', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Suối Rao', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Sơn Bình', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Xã Xà Bang', 'id_quan_huyen' => 9],
['ten_phuong_xa' => 'Thị trấn Phước Bửu', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Bàu Lâm', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Bông Trang', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Bưng Riềng', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Hòa Bình', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Hòa Hiệp', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Hòa Hội', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Hòa Hưng', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Hòa Tân', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Phước Tân', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Xã Phước Thuận', 'id_quan_huyen' => 10],
['ten_phuong_xa' => 'Thị trấn Đất Đỏ', 'id_quan_huyen' => 11],
['ten_phuong_xa' => 'Thị trấn Phước Hải', 'id_quan_huyen' => 11],
['ten_phuong_xa' => 'Xã Long Mỹ', 'id_quan_huyen' => 11],
['ten_phuong_xa' => 'Xã Láng Dài', 'id_quan_huyen' => 11],
['ten_phuong_xa' => 'Xã Lộc An', 'id_quan_huyen' => 11],
['ten_phuong_xa' => 'Xã Phước Hội', 'id_quan_huyen' => 11],
['ten_phuong_xa' => 'Xã Phước Long Thọ', 'id_quan_huyen' => 11],
['ten_phuong_xa' => 'Phường 1', 'id_quan_huyen' => 12],
['ten_phuong_xa' => 'Phường 2', 'id_quan_huyen' => 12],
['ten_phuong_xa' => 'Phường 3', 'id_quan_huyen' => 12],
['ten_phuong_xa' => 'Phường 5', 'id_quan_huyen' => 12],
['ten_phuong_xa' => 'Phường 7', 'id_quan_huyen' => 12],
['ten_phuong_xa' => 'Phường 8', 'id_quan_huyen' => 12],
['ten_phuong_xa' => 'Xã Hiệp Thành', 'id_quan_huyen' => 12],
['ten_phuong_xa' => 'Xã Nhà Mát', 'id_quan_huyen' => 12],
['ten_phuong_xa' => 'Thị trấn Hòa Bình', 'id_quan_huyen' => 13],
['ten_phuong_xa' => 'Xã Minh Diệu', 'id_quan_huyen' => 13],
['ten_phuong_xa' => 'Xã Vĩnh Bình', 'id_quan_huyen' => 13],
['ten_phuong_xa' => 'Xã Vĩnh Hậu', 'id_quan_huyen' => 13],
['ten_phuong_xa' => 'Xã Vĩnh Hậu A', 'id_quan_huyen' => 13],
['ten_phuong_xa' => 'Xã Vĩnh Mỹ A', 'id_quan_huyen' => 13],
['ten_phuong_xa' => 'Xã Vĩnh Mỹ B', 'id_quan_huyen' => 13],
['ten_phuong_xa' => 'Thị trấn Phước Long', 'id_quan_huyen' => 14],
['ten_phuong_xa' => 'Xã Hưng Phú', 'id_quan_huyen' => 14],
['ten_phuong_xa' => 'Xã Phong Thạnh Tây A', 'id_quan_huyen' => 14],
['ten_phuong_xa' => 'Xã Phong Thạnh Tây B', 'id_quan_huyen' => 14],
['ten_phuong_xa' => 'Xã Vĩnh Phú Đông', 'id_quan_huyen' => 14],
['ten_phuong_xa' => 'Xã Vĩnh Phú Tây', 'id_quan_huyen' => 14],
['ten_phuong_xa' => 'Xã Vĩnh Thanh', 'id_quan_huyen' => 14],
['ten_phuong_xa' => 'Thị trấn Châu Hưng', 'id_quan_huyen' => 15],
['ten_phuong_xa' => 'Xã Châu Hưng A', 'id_quan_huyen' => 15],
['ten_phuong_xa' => 'Xã Hưng Hội', 'id_quan_huyen' => 15],
['ten_phuong_xa' => 'Xã Hưng Thành', 'id_quan_huyen' => 15],
['ten_phuong_xa' => 'Xã Long Thạnh', 'id_quan_huyen' => 15],
['ten_phuong_xa' => 'Xã Vĩnh Hưng', 'id_quan_huyen' => 15],
['ten_phuong_xa' => 'Xã Vĩnh Hưng A', 'id_quan_huyen' => 15],
['ten_phuong_xa' => 'Xã Vĩnh Lợi', 'id_quan_huyen' => 15],
['ten_phuong_xa' => 'Thị trấn Ngan Dừa', 'id_quan_huyen' => 16],
['ten_phuong_xa' => 'Xã Lộc Ninh', 'id_quan_huyen' => 16],
['ten_phuong_xa' => 'Xã Ninh Hòa', 'id_quan_huyen' => 16],
['ten_phuong_xa' => 'Xã Ninh Quới', 'id_quan_huyen' => 16],
['ten_phuong_xa' => 'Xã Ninh Quới A', 'id_quan_huyen' => 16],
['ten_phuong_xa' => 'Xã Ninh Thạnh Lợi', 'id_quan_huyen' => 16],
['ten_phuong_xa' => 'Xã Ninh Thạnh Lợi A', 'id_quan_huyen' => 16],
['ten_phuong_xa' => 'Xã Vĩnh Lộc', 'id_quan_huyen' => 16],
['ten_phuong_xa' => 'Xã Vĩnh Lộc A', 'id_quan_huyen' => 16],
['ten_phuong_xa' => 'Phường 1', 'id_quan_huyen' => 17],
['ten_phuong_xa' => 'Phường Hộ Phòng', 'id_quan_huyen' => 17],
['ten_phuong_xa' => 'Phường Láng Tròn', 'id_quan_huyen' => 17],
['ten_phuong_xa' => 'Xã Phong Thạnh', 'id_quan_huyen' => 17],
['ten_phuong_xa' => 'Xã Phong Thạnh A', 'id_quan_huyen' => 17],
['ten_phuong_xa' => 'Xã Phong Thạnh Đông', 'id_quan_huyen' => 17],
['ten_phuong_xa' => 'Xã Phong Tân', 'id_quan_huyen' => 17],
['ten_phuong_xa' => 'Xã Tân Phong', 'id_quan_huyen' => 17],
['ten_phuong_xa' => 'Phường Nguyễn Thị Minh Khai', 'id_quan_huyen' => 18],
['ten_phuong_xa' => 'Phường Đức Xuân', 'id_quan_huyen' => 18],
['ten_phuong_xa' => 'Phường Sông Cầu', 'id_quan_huyen' => 18],
['ten_phuong_xa' => 'Phường Phùng Chí Kiên', 'id_quan_huyen' => 18],
['ten_phuong_xa' => 'Xã Dương Quang', 'id_quan_huyen' => 18],
['ten_phuong_xa' => 'Xã Nông Thượng', 'id_quan_huyen' => 18],
['ten_phuong_xa' => 'Thị trấn Chợ Mới', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Quảng Chu', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Yên Đĩnh', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Như Cố', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Bình Văn', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Yên Hân', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Thanh Bình', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Nông Hạ', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Nông Thịnh', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Cao Kỳ', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Tân Sơn', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Hòa Mục', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Thanh Vận', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Thị trấn Chợ Mới', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Quảng Chu', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Yên Đĩnh', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Như Cố', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Bình Văn', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Yên Hân', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Thanh Bình', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Nông Hạ', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Nông Thịnh', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Cao Kỳ', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Tân Sơn', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Hòa Mục', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Xã Thanh Vận', 'id_quan_huyen' => 19],
['ten_phuong_xa' => 'Thị trấn Pác Nặm', 'id_quan_huyen' => 21],
['ten_phuong_xa' => 'Xã Pác Nặm', 'id_quan_huyen' => 21],
['ten_phuong_xa' => 'Xã Nghiên Loan', 'id_quan_huyen' => 21],
['ten_phuong_xa' => 'Xã Cao Sơn', 'id_quan_huyen' => 21],
['ten_phuong_xa' => 'Xã Hương Sơn', 'id_quan_huyen' => 21],
['ten_phuong_xa' => 'Xã Quảng Vịnh', 'id_quan_huyen' => 21],
['ten_phuong_xa' => 'Thị trấn Na Rì', 'id_quan_huyen' => 22],
['ten_phuong_xa' => 'Xã Phúc Lợi', 'id_quan_huyen' => 22],
['ten_phuong_xa' => 'Xã Đồng Tâm', 'id_quan_huyen' => 22],
['ten_phuong_xa' => 'Xã Kim Đồng', 'id_quan_huyen' => 22],
['ten_phuong_xa' => 'Xã Chí Thượng', 'id_quan_huyen' => 22],
['ten_phuong_xa' => 'Xã Yên Sơn', 'id_quan_huyen' => 22],
['ten_phuong_xa' => 'Xã Cao Minh', 'id_quan_huyen' => 22],
['ten_phuong_xa' => 'Xã Văn Hương', 'id_quan_huyen' => 22],
['ten_phuong_xa' => 'Thị trấn Chợ Rã', 'id_quan_huyen' => 23],
['ten_phuong_xa' => 'Xã Bằng Lãng', 'id_quan_huyen' => 23],
['ten_phuong_xa' => 'Xã Bằng Phúc', 'id_quan_huyen' => 23],
['ten_phuong_xa' => 'Xã Cao Trĩ', 'id_quan_huyen' => 23],
['ten_phuong_xa' => 'Xã Hà Hiệu', 'id_quan_huyen' => 23],
['ten_phuong_xa' => 'Xã Hương Linh', 'id_quan_huyen' => 23],
['ten_phuong_xa' => 'Xã Khang Ninh', 'id_quan_huyen' => 23],
['ten_phuong_xa' => 'Xã Nam Mẫu', 'id_quan_huyen' => 23],
['ten_phuong_xa' => 'Thị trấn Ngân Sơn', 'id_quan_huyen' => 24],
['ten_phuong_xa' => 'Xã Bằng Vân', 'id_quan_huyen' => 24],
['ten_phuong_xa' => 'Xã Cổ Linh', 'id_quan_huyen' => 24],
['ten_phuong_xa' => 'Xã Thượng Quan', 'id_quan_huyen' => 24],
['ten_phuong_xa' => 'Xã Bình Trung', 'id_quan_huyen' => 24],
['ten_phuong_xa' => 'Xã Vũ Lễ', 'id_quan_huyen' => 24],
['ten_phuong_xa' => 'Thị trấn Bắc Giang', 'id_quan_huyen' => 25],
['ten_phuong_xa' => 'Xã Tân Mỹ', 'id_quan_huyen' => 25],
['ten_phuong_xa' => 'Xã Dĩnh Kế', 'id_quan_huyen' => 25],
['ten_phuong_xa' => 'Xã Quang Thịnh', 'id_quan_huyen' => 25],
['ten_phuong_xa' => 'Xã Vân Trung', 'id_quan_huyen' => 25],
['ten_phuong_xa' => 'Xã Xương Giang', 'id_quan_huyen' => 25],
['ten_phuong_xa' => 'Thị trấn Lục Nam', 'id_quan_huyen' => 26],
['ten_phuong_xa' => 'Xã Lục Sơn', 'id_quan_huyen' => 26],
['ten_phuong_xa' => 'Xã Phú Hộ', 'id_quan_huyen' => 26],
['ten_phuong_xa' => 'Xã Tiến Thắng', 'id_quan_huyen' => 26],
['ten_phuong_xa' => 'Xã Lục Thịnh', 'id_quan_huyen' => 26],
['ten_phuong_xa' => 'Thị trấn Lạng Giang', 'id_quan_huyen' => 27],
['ten_phuong_xa' => 'Xã Tiến Dũng', 'id_quan_huyen' => 27],
['ten_phuong_xa' => 'Xã Tân Dĩnh', 'id_quan_huyen' => 27],
['ten_phuong_xa' => 'Xã Nghĩa Hòa', 'id_quan_huyen' => 27],
['ten_phuong_xa' => 'Xã Hương Sơn', 'id_quan_huyen' => 27],
['ten_phuong_xa' => 'Thị trấn Yên Dũng', 'id_quan_huyen' => 28],
['ten_phuong_xa' => 'Xã Yên Thịnh', 'id_quan_huyen' => 28],
['ten_phuong_xa' => 'Xã Tiến Hòa', 'id_quan_huyen' => 28],
['ten_phuong_xa' => 'Xã Đồng Cẩm', 'id_quan_huyen' => 28],
['ten_phuong_xa' => 'Xã Vĩnh Phúc', 'id_quan_huyen' => 28],
['ten_phuong_xa' => 'Thị trấn An Châu', 'id_quan_huyen' => 29],
['ten_phuong_xa' => 'Xã Sơn Hải', 'id_quan_huyen' => 29],
['ten_phuong_xa' => 'Xã Vũ Xá', 'id_quan_huyen' => 29],
['ten_phuong_xa' => 'Xã Thạch Lỗi', 'id_quan_huyen' => 29],
['ten_phuong_xa' => 'Xã Bắc Sơn', 'id_quan_huyen' => 29],
['ten_phuong_xa' => 'Thị trấn Thắng', 'id_quan_huyen' => 30],
['ten_phuong_xa' => 'Xã Hương Lạc', 'id_quan_huyen' => 30],
['ten_phuong_xa' => 'Xã Mai Đình', 'id_quan_huyen' => 30],
['ten_phuong_xa' => 'Xã Hiệp Thắng', 'id_quan_huyen' => 30],
['ten_phuong_xa' => 'Xã Ngọc Sơn', 'id_quan_huyen' => 30],
['ten_phuong_xa' => 'Thị trấn Tân Yên', 'id_quan_huyen' => 31],
['ten_phuong_xa' => 'Xã Quế Nham', 'id_quan_huyen' => 31],
['ten_phuong_xa' => 'Xã Lan Mẫu', 'id_quan_huyen' => 31],
['ten_phuong_xa' => 'Xã Nghĩa Hưng', 'id_quan_huyen' => 31],
['ten_phuong_xa' => 'Xã Bảo Sơn', 'id_quan_huyen' => 31],
['ten_phuong_xa' => 'Thị trấn Bích Động', 'id_quan_huyen' => 32],
['ten_phuong_xa' => 'Xã Tự Lập', 'id_quan_huyen' => 32],
['ten_phuong_xa' => 'Xã Vân Trung', 'id_quan_huyen' => 32],
['ten_phuong_xa' => 'Xã Hương Mai', 'id_quan_huyen' => 32],
['ten_phuong_xa' => 'Xã Minh Đức', 'id_quan_huyen' => 32],
['ten_phuong_xa' => 'Thị trấn Chũ', 'id_quan_huyen' => 33],
['ten_phuong_xa' => 'Xã Nam Dương', 'id_quan_huyen' => 33],
['ten_phuong_xa' => 'Xã Phượng Sơn', 'id_quan_huyen' => 33],
['ten_phuong_xa' => 'Xã Tân Lập', 'id_quan_huyen' => 33],
['ten_phuong_xa' => 'Xã Lục Sơn', 'id_quan_huyen' => 33],
['ten_phuong_xa' => 'Thị trấn Yên Thế', 'id_quan_huyen' => 34],
['ten_phuong_xa' => 'Xã Tân Hiệp', 'id_quan_huyen' => 34],
['ten_phuong_xa' => 'Xã Đông Sơn', 'id_quan_huyen' => 34],
['ten_phuong_xa' => 'Xã Cẩm Lý', 'id_quan_huyen' => 34],
['ten_phuong_xa' => 'Xã Lương Phong', 'id_quan_huyen' => 34],
['ten_phuong_xa' => 'Phường Suối Hoa', 'id_quan_huyen' => 35],
['ten_phuong_xa' => 'Phường Đại Phúc', 'id_quan_huyen' => 35],
['ten_phuong_xa' => 'Xã Hoài Thượng', 'id_quan_huyen' => 35],
['ten_phuong_xa' => 'Xã Vân Dương', 'id_quan_huyen' => 35],
['ten_phuong_xa' => 'Thị trấn Gia Bình', 'id_quan_huyen' => 36],
['ten_phuong_xa' => 'Xã Bình Dương', 'id_quan_huyen' => 36],
['ten_phuong_xa' => 'Xã Quỳnh Phú', 'id_quan_huyen' => 36],
['ten_phuong_xa' => 'Xã Đại Bái', 'id_quan_huyen' => 36],
['ten_phuong_xa' => 'Thị trấn Phố Mới', 'id_quan_huyen' => 37],
['ten_phuong_xa' => 'Xã Bình Định', 'id_quan_huyen' => 37],
['ten_phuong_xa' => 'Xã Quế Tân', 'id_quan_huyen' => 37],
['ten_phuong_xa' => 'Xã Phương Liễu', 'id_quan_huyen' => 37],
['ten_phuong_xa' => 'Thị trấn Lim', 'id_quan_huyen' => 38],
['ten_phuong_xa' => 'Xã Hoàn Sơn', 'id_quan_huyen' => 38],
['ten_phuong_xa' => 'Xã Cảnh Hưng', 'id_quan_huyen' => 38],
['ten_phuong_xa' => 'Xã Tiên Sơn', 'id_quan_huyen' => 38],
['ten_phuong_xa' => 'Thị trấn Hồ', 'id_quan_huyen' => 39],
['ten_phuong_xa' => 'Xã Đại Đồng Thành', 'id_quan_huyen' => 39],
['ten_phuong_xa' => 'Xã Xuân Lâm', 'id_quan_huyen' => 39],
['ten_phuong_xa' => 'Xã An Bình', 'id_quan_huyen' => 39],
['ten_phuong_xa' => 'Thị trấn Yên Phong', 'id_quan_huyen' => 40],
['ten_phuong_xa' => 'Xã Đông Tiến', 'id_quan_huyen' => 40],
['ten_phuong_xa' => 'Xã Yên Giả', 'id_quan_huyen' => 40],
['ten_phuong_xa' => 'Xã Long Châu', 'id_quan_huyen' => 40],
['ten_phuong_xa' => 'Thị trấn Lương Tài', 'id_quan_huyen' => 41],
['ten_phuong_xa' => 'Xã Phú Lâm', 'id_quan_huyen' => 41],
['ten_phuong_xa' => 'Xã Lương Phong', 'id_quan_huyen' => 41],
['ten_phuong_xa' => 'Xã Bình Dương', 'id_quan_huyen' => 41],
['ten_phuong_xa' => 'Phường 1', 'id_quan_huyen' => 42],
['ten_phuong_xa' => 'Phường 2', 'id_quan_huyen' => 42],
['ten_phuong_xa' => 'Phường 3', 'id_quan_huyen' => 42],
['ten_phuong_xa' => 'Xã Mỹ Thạnh An', 'id_quan_huyen' => 42],


['ten_phuong_xa' => 'Thị trấn Châu Thành', 'id_quan_huyen' => 43],
['ten_phuong_xa' => 'Xã An Hữu', 'id_quan_huyen' => 43],
['ten_phuong_xa' => 'Xã Tam Hiệp', 'id_quan_huyen' => 43],
['ten_phuong_xa' => 'Xã Quới Sơn', 'id_quan_huyen' => 43],
['ten_phuong_xa' => 'Thị trấn Chợ Lách', 'id_quan_huyen' => 44],
['ten_phuong_xa' => 'Xã Vĩnh Thành', 'id_quan_huyen' => 44],
['ten_phuong_xa' => 'Xã Phú Lễ', 'id_quan_huyen' => 44],
['ten_phuong_xa' => 'Xã Sơn Định', 'id_quan_huyen' => 44],
['ten_phuong_xa' => 'Thị trấn Giồng Trôm', 'id_quan_huyen' => 45],
['ten_phuong_xa' => 'Xã Bình Hoà', 'id_quan_huyen' => 45],
['ten_phuong_xa' => 'Xã Tân Thanh', 'id_quan_huyen' => 45],
['ten_phuong_xa' => 'Xã Lương Hòa', 'id_quan_huyen' => 45],
['ten_phuong_xa' => 'Thị trấn Mỏ Cày', 'id_quan_huyen' => 46],
['ten_phuong_xa' => 'Xã An Thạnh', 'id_quan_huyen' => 46],
['ten_phuong_xa' => 'Xã Minh Đức', 'id_quan_huyen' => 46],
['ten_phuong_xa' => 'Xã Lộc Thuận', 'id_quan_huyen' => 46],
['ten_phuong_xa' => 'Thị trấn Mỏ Cày Nam', 'id_quan_huyen' => 47],
['ten_phuong_xa' => 'Xã An Bình', 'id_quan_huyen' => 47],
['ten_phuong_xa' => 'Xã Định Thủy', 'id_quan_huyen' => 47],
['ten_phuong_xa' => 'Xã Thạnh Phú', 'id_quan_huyen' => 47],


    ['ten_phuong_xa' => 'Thị trấn Ba Tri', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã An Phú Trung', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Bình Thạnh', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Bảo Thạnh', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Mỹ Chánh', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Phú Lễ', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Phú Long', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Sơn Hòa', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Tân Hưng', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Tam Hiệp', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Mỹ Thành', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Tân Phú', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã An Đức', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Vĩnh Hòa', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Hòa Lộc', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã An Ngãi', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Tân An', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Xã Hưng Khánh Trung B', 'id_quan_huyen' => 48],
    ['ten_phuong_xa' => 'Thị trấn Bảo Thạnh', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã An Phú', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã An Thạnh', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã Bảo Thạnh', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã Phú Lễ', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã Phú Long', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã Sơn Đông', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã Tân Phú', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã An Thủy', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã Vĩnh Hòa', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Xã Hòa Lộc', 'id_quan_huyen' => 49],
    ['ten_phuong_xa' => 'Thị trấn Thạnh Phú', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã An Nhơn', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã An Hiệp', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã Bình Thạnh', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã Giao Thạnh', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã Phú Khánh', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã Quới Sơn', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã Mỹ An', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã Tân Phong', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã Vĩnh An', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã Thạnh Quới', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Xã Hòa Lộc', 'id_quan_huyen' => 50],
    ['ten_phuong_xa' => 'Phường Phú Cường', 'id_quan_huyen' => 51],
    ['ten_phuong_xa' => 'Phường Hiệp Thành', 'id_quan_huyen' => 51],
    ['ten_phuong_xa' => 'Phường Chánh Nghĩa', 'id_quan_huyen' => 51],
    ['ten_phuong_xa' => 'Phường Tương Bình Hiệp', 'id_quan_huyen' => 51],
    ['ten_phuong_xa' => 'Phường Phú Lợi', 'id_quan_huyen' => 51],
    ['ten_phuong_xa' => 'Phường Hòa Phú', 'id_quan_huyen' => 51],
    ['ten_phuong_xa' => 'Phường Định Hòa', 'id_quan_huyen' => 51],
    ['ten_phuong_xa' => 'Phường Bình Hòa', 'id_quan_huyen' => 52],
    ['ten_phuong_xa' => 'Phường Đông Hòa', 'id_quan_huyen' => 52],
    ['ten_phuong_xa' => 'Phường Dĩ An', 'id_quan_huyen' => 52],
    ['ten_phuong_xa' => 'Phường Tân Bình', 'id_quan_huyen' => 52],
    ['ten_phuong_xa' => 'Xã An Bình', 'id_quan_huyen' => 52],
    ['ten_phuong_xa' => 'Xã Bình Mỹ', 'id_quan_huyen' => 53],
    ['ten_phuong_xa' => 'Xã Hòa Lợi', 'id_quan_huyen' => 53],
    ['ten_phuong_xa' => 'Xã An Điền', 'id_quan_huyen' => 53],
    ['ten_phuong_xa' => 'Xã Tân Định', 'id_quan_huyen' => 53],
    ['ten_phuong_xa' => 'Xã Bình Hòa', 'id_quan_huyen' => 53],
    ['ten_phuong_xa' => 'Phường Lái Thiêu', 'id_quan_huyen' => 54],
    ['ten_phuong_xa' => 'Phường Bình Hòa', 'id_quan_huyen' => 54],
    ['ten_phuong_xa' => 'Phường An Phú', 'id_quan_huyen' => 54],
    ['ten_phuong_xa' => 'Phường Hưng Định', 'id_quan_huyen' => 54],
    ['ten_phuong_xa' => 'Phường Vĩnh Phú', 'id_quan_huyen' => 54],
    ['ten_phuong_xa' => 'Phường Bình Chuẩn', 'id_quan_huyen' => 54],
    ['ten_phuong_xa' => 'Phường An Thạnh', 'id_quan_huyen' => 54],
    ['ten_phuong_xa' => 'Phường Thuận Giao', 'id_quan_huyen' => 54],
    ['ten_phuong_xa' => 'Phường Đông Hòa', 'id_quan_huyen' => 55],
    ['ten_phuong_xa' => 'Phường Tân Hiệp', 'id_quan_huyen' => 55],
    ['ten_phuong_xa' => 'Phường Uyên Hưng', 'id_quan_huyen' => 55],
    ['ten_phuong_xa' => 'Phường Thạnh Phước', 'id_quan_huyen' => 55],
    ['ten_phuong_xa' => 'Phường Tân Thành', 'id_quan_huyen' => 55],
    ['ten_phuong_xa' => 'Xã Vĩnh Tân', 'id_quan_huyen' => 55],
    ['ten_phuong_xa' => 'Xã Thái Hòa', 'id_quan_huyen' => 55],
    ['ten_phuong_xa' => 'Xã Bạch Đằng', 'id_quan_huyen' => 55],
    ['ten_phuong_xa' => 'Xã An Bình', 'id_quan_huyen' => 56],
    ['ten_phuong_xa' => 'Xã Phú An', 'id_quan_huyen' => 56],
    ['ten_phuong_xa' => 'Xã Tân Long', 'id_quan_huyen' => 56],
    ['ten_phuong_xa' => 'Xã Vĩnh Hòa', 'id_quan_huyen' => 56],
    ['ten_phuong_xa' => 'Xã Thạnh Hội', 'id_quan_huyen' => 56],
    ['ten_phuong_xa' => 'Xã Minh Hòa', 'id_quan_huyen' => 56],
    ['ten_phuong_xa' => 'Xã Phước Hòa', 'id_quan_huyen' => 56],
    ['ten_phuong_xa' => 'Xã Tân Thành', 'id_quan_huyen' => 56],
    ['ten_phuong_xa' => 'Xã Bạch Đằng', 'id_quan_huyen' => 57],
    ['ten_phuong_xa' => 'Xã Lai Uyên', 'id_quan_huyen' => 57],
    ['ten_phuong_xa' => 'Xã Cây Trường', 'id_quan_huyen' => 57],
    ['ten_phuong_xa' => 'Xã Long Nguyên', 'id_quan_huyen' => 57],
    ['ten_phuong_xa' => 'Xã An Lập', 'id_quan_huyen' => 57],
    ['ten_phuong_xa' => 'Xã Phú An', 'id_quan_huyen' => 57],
    ['ten_phuong_xa' => 'Phường Ghềnh Ráng', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Phường Trần Quang Diệu', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Phường Quang Trung', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Phường Lý Thường Kiệt', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Phường Nguyễn Văn Cừ', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Phường Hải Cảng', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Phường Đống Đa', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Phường Thị Nại', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Xã Nhơn Lý', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Xã Nhơn Hải', 'id_quan_huyen' => 58],
    ['ten_phuong_xa' => 'Xã Phước Sơn', 'id_quan_huyen' => 59],
    ['ten_phuong_xa' => 'Xã An Lão', 'id_quan_huyen' => 59],
    ['ten_phuong_xa' => 'Xã Cát Nhơn', 'id_quan_huyen' => 60],
    ['ten_phuong_xa' => 'Xã Hoài Hải', 'id_quan_huyen' => 60],
    ['ten_phuong_xa' => 'Xã Hoài Mỹ', 'id_quan_huyen' => 60],
    ['ten_phuong_xa' => 'Xã Hoài Hảo', 'id_quan_huyen' => 60],
    ['ten_phuong_xa' => 'Xã Cát Tân', 'id_quan_huyen' => 61],
    ['ten_phuong_xa' => 'Xã Cát Hiệp', 'id_quan_huyen' => 61],
    ['ten_phuong_xa' => 'Xã Cát Thành', 'id_quan_huyen' => 61],
    ['ten_phuong_xa' => 'Xã Cát Quang', 'id_quan_huyen' => 62],
    ['ten_phuong_xa' => 'Xã Cát Tường', 'id_quan_huyen' => 62],
    ['ten_phuong_xa' => 'Xã Cát Hòa', 'id_quan_huyen' => 62],
    ['ten_phuong_xa' => 'Xã Cát Sơn', 'id_quan_huyen' => 62],
    ['ten_phuong_xa' => 'Xã Cát Chánh', 'id_quan_huyen' => 62],
    ['ten_phuong_xa' => 'Xã Phước Hiệp', 'id_quan_huyen' => 63],
    ['ten_phuong_xa' => 'Xã Tây Giang', 'id_quan_huyen' => 63],
    ['ten_phuong_xa' => 'Xã Tây Vinh', 'id_quan_huyen' => 63],
    ['ten_phuong_xa' => 'Xã Tây Tân', 'id_quan_huyen' => 63],
    ['ten_phuong_xa' => 'Xã Tây Phú', 'id_quan_huyen' => 63],
    ['ten_phuong_xa' => 'Xã Vân Sơn', 'id_quan_huyen' => 64],
    ['ten_phuong_xa' => 'Xã Vân Tường', 'id_quan_huyen' => 64],
    ['ten_phuong_xa' => 'Xã Vân Hội', 'id_quan_huyen' => 64],
    ['ten_phuong_xa' => 'Xã Hoài Châu', 'id_quan_huyen' => 65],
    ['ten_phuong_xa' => 'Xã Hoài Phú', 'id_quan_huyen' => 65],
    ['ten_phuong_xa' => 'Xã Hoài Thắng', 'id_quan_huyen' => 65],
    ['ten_phuong_xa' => 'Xã Hoài Châu Bắc', 'id_quan_huyen' => 65],
    ['ten_phuong_xa' => 'Xã Hoài Sơn', 'id_quan_huyen' => 65],
    ['ten_phuong_xa' => 'Xã Xuân Phú', 'id_quan_huyen' => 66],
    ['ten_phuong_xa' => 'Xã Xuân Hòa', 'id_quan_huyen' => 66],
    ['ten_phuong_xa' => 'Phường Phú Hòa', 'id_quan_huyen' => 67],
    ['ten_phuong_xa' => 'Phường Tân Bình', 'id_quan_huyen' => 67],
    ['ten_phuong_xa' => 'Phường Hiệp Thành', 'id_quan_huyen' => 67],
    ['ten_phuong_xa' => 'Phường Chánh Nghĩa', 'id_quan_huyen' => 67],
    ['ten_phuong_xa' => 'Phường Lái Thiêu', 'id_quan_huyen' => 67],
    ['ten_phuong_xa' => 'Phường An Phú', 'id_quan_huyen' => 67],
    ['ten_phuong_xa' => 'Phường Bình An', 'id_quan_huyen' => 67],
    ['ten_phuong_xa' => 'Xã Tân An', 'id_quan_huyen' => 68],
    ['ten_phuong_xa' => 'Xã Lộc Thịnh', 'id_quan_huyen' => 68],
    ['ten_phuong_xa' => 'Xã Bình Long', 'id_quan_huyen' => 69],
    ['ten_phuong_xa' => 'Xã Phú Riềng', 'id_quan_huyen' => 69],
    ['ten_phuong_xa' => 'Xã Đồng Tiến', 'id_quan_huyen' => 69],
    ['ten_phuong_xa' => 'Xã Minh Tâm', 'id_quan_huyen' => 69],
    ['ten_phuong_xa' => 'Xã Tân Tiến', 'id_quan_huyen' => 69],
    ['ten_phuong_xa' => 'Xã An Phú', 'id_quan_huyen' => 70],
    ['ten_phuong_xa' => 'Xã Chơn Thành', 'id_quan_huyen' => 70],
    ['ten_phuong_xa' => 'Xã Minh Hưng', 'id_quan_huyen' => 70],
    ['ten_phuong_xa' => 'Xã Hưng Hòa', 'id_quan_huyen' => 70],
    ['ten_phuong_xa' => 'Xã Phước Long', 'id_quan_huyen' => 71],
    ['ten_phuong_xa' => 'Xã Bình Tâm', 'id_quan_huyen' => 71],
    ['ten_phuong_xa' => 'Xã Thanh Bình', 'id_quan_huyen' => 71],
    ['ten_phuong_xa' => 'Xã Tân Hiệp', 'id_quan_huyen' => 71],
    ['ten_phuong_xa' => 'Xã Tân Phú', 'id_quan_huyen' => 71],
    ['ten_phuong_xa' => 'Xã Minh Hưng', 'id_quan_huyen' => 71],
    ['ten_phuong_xa' => 'Xã Phú Mỹ', 'id_quan_huyen' => 71],
    ['ten_phuong_xa' => 'Xã Bù Gia Mập', 'id_quan_huyen' => 72],
    ['ten_phuong_xa' => 'Xã Đức Hạnh', 'id_quan_huyen' => 72],
    ['ten_phuong_xa' => 'Xã Phú Văn', 'id_quan_huyen' => 72],
    ['ten_phuong_xa' => 'Xã Bù Gia Mập', 'id_quan_huyen' => 72],
    ['ten_phuong_xa' => 'Xã Bình Minh', 'id_quan_huyen' => 72],
    ['ten_phuong_xa' => 'Xã Bù Đăng', 'id_quan_huyen' => 73],
    ['ten_phuong_xa' => 'Xã Phước An', 'id_quan_huyen' => 73],
    ['ten_phuong_xa' => 'Xã Phú Sơn', 'id_quan_huyen' => 73],
    ['ten_phuong_xa' => 'Xã Đức Liễu', 'id_quan_huyen' => 73],
    ['ten_phuong_xa' => 'Xã Bù Gia', 'id_quan_huyen' => 73],
    ['ten_phuong_xa' => 'Xã Lộc An', 'id_quan_huyen' => 74],
    ['ten_phuong_xa' => 'Xã Lộc Tấn', 'id_quan_huyen' => 74],
    ['ten_phuong_xa' => 'Xã Lộc Hòa', 'id_quan_huyen' => 74],
    ['ten_phuong_xa' => 'Xã Lộc Quả', 'id_quan_huyen' => 74],
    ['ten_phuong_xa' => 'Xã Lộc Thái', 'id_quan_huyen' => 74],
    ['ten_phuong_xa' => 'Phường Bình Hưng', 'id_quan_huyen' => 75],
    ['ten_phuong_xa' => 'Phường Phú Thủy', 'id_quan_huyen' => 75],
    ['ten_phuong_xa' => 'Phường Thanh Hải', 'id_quan_huyen' => 75],
    ['ten_phuong_xa' => 'Phường Phú Tài', 'id_quan_huyen' => 75],
    ['ten_phuong_xa' => 'Phường Xuân An', 'id_quan_huyen' => 75],
    ['ten_phuong_xa' => 'Phường Hàm Tiến', 'id_quan_huyen' => 75],
    ['ten_phuong_xa' => 'Phường Mũi Né', 'id_quan_huyen' => 75],
    ['ten_phuong_xa' => 'Xã Tân Tiến', 'id_quan_huyen' => 76],
    ['ten_phuong_xa' => 'Xã Tân Hải', 'id_quan_huyen' => 76],
    ['ten_phuong_xa' => 'Xã Phước Lộc', 'id_quan_huyen' => 77],
    ['ten_phuong_xa' => 'Xã Tánh Linh', 'id_quan_huyen' => 77],
    ['ten_phuong_xa' => 'Xã Hàm Kiệm', 'id_quan_huyen' => 78],
    ['ten_phuong_xa' => 'Xã La Gi', 'id_quan_huyen' => 79],
    ['ten_phuong_xa' => 'Xã Bình Tân', 'id_quan_huyen' => 79],
    ['ten_phuong_xa' => 'Xã Bình Chánh', 'id_quan_huyen' => 79],
    ['ten_phuong_xa' => 'Xã Hàm Chính', 'id_quan_huyen' => 80],
    ['ten_phuong_xa' => 'Xã Hàm Liêm', 'id_quan_huyen' => 80],
    ['ten_phuong_xa' => 'Xã Hàm Thắng', 'id_quan_huyen' => 80],
    ['ten_phuong_xa' => 'Xã Hàm Hiệp', 'id_quan_huyen' => 80],
    ['ten_phuong_xa' => 'Xã Mương Mán', 'id_quan_huyen' => 80],
    ['ten_phuong_xa' => 'Xã Thị trấn Ma Lâm', 'id_quan_huyen' => 81],
    ['ten_phuong_xa' => 'Xã Tân Tiến', 'id_quan_huyen' => 81],
    ['ten_phuong_xa' => 'Xã Mương Mán', 'id_quan_huyen' => 81],
    ['ten_phuong_xa' => 'Xã La Dạ', 'id_quan_huyen' => 82],
    ['ten_phuong_xa' => 'Xã Đức Linh', 'id_quan_huyen' => 82],
    ['ten_phuong_xa' => 'Xã Đức Hòa', 'id_quan_huyen' => 83],
    ['ten_phuong_xa' => 'Xã Đức Minh', 'id_quan_huyen' => 83],
    ['ten_phuong_xa' => 'Xã Tân Bình', 'id_quan_huyen' => 83],
    ['ten_phuong_xa' => 'Xã Phú Quí', 'id_quan_huyen' => 84],
    ['ten_phuong_xa' => 'Xã Bình Thạnh', 'id_quan_huyen' => 84],
    ['ten_phuong_xa' => 'Xã Đảo Phú Quí', 'id_quan_huyen' => 84],
    ['ten_phuong_xa' => 'Phường 1', 'id_quan_huyen' => 85],
    ['ten_phuong_xa' => 'Phường 2', 'id_quan_huyen' => 85],
    ['ten_phuong_xa' => 'Phường 3', 'id_quan_huyen' => 85],
    ['ten_phuong_xa' => 'Phường 4', 'id_quan_huyen' => 85],
    ['ten_phuong_xa' => 'Phường 5', 'id_quan_huyen' => 85],
    ['ten_phuong_xa' => 'Phường 6', 'id_quan_huyen' => 85],
    ['ten_phuong_xa' => 'Phường 7', 'id_quan_huyen' => 85],
    ['ten_phuong_xa' => 'Phường 8', 'id_quan_huyen' => 85],
    ['ten_phuong_xa' => 'Xã Lý Văn Lâm', 'id_quan_huyen' => 86],
    ['ten_phuong_xa' => 'Xã An Xuyên', 'id_quan_huyen' => 86],
    ['ten_phuong_xa' => 'Xã Tắc Vân', 'id_quan_huyen' => 87],
    ['ten_phuong_xa' => 'Xã Khánh Bình', 'id_quan_huyen' => 87],
    ['ten_phuong_xa' => 'Xã U Minh', 'id_quan_huyen' => 88],
    ['ten_phuong_xa' => 'Xã Hòa Tân', 'id_quan_huyen' => 88],
    ['ten_phuong_xa' => 'Xã Khánh An', 'id_quan_huyen' => 89],
    ['ten_phuong_xa' => 'Xã Thới Bình', 'id_quan_huyen' => 90],
    ['ten_phuong_xa' => 'Xã Tân Bằng', 'id_quan_huyen' => 90],
    ['ten_phuong_xa' => 'Xã Biển Bạch', 'id_quan_huyen' => 90],
    ['ten_phuong_xa' => 'Xã Hòa Bình', 'id_quan_huyen' => 90],
    ['ten_phuong_xa' => 'Xã Tân Lộc', 'id_quan_huyen' => 90],
    ['ten_phuong_xa' => 'Xã Trần Phán', 'id_quan_huyen' => 91],
    ['ten_phuong_xa' => 'Xã Lợi An', 'id_quan_huyen' => 91],
    ['ten_phuong_xa' => 'Xã Bình Thạnh', 'id_quan_huyen' => 91],
    ['ten_phuong_xa' => 'Xã Phú Mỹ', 'id_quan_huyen' => 91],
    ['ten_phuong_xa' => 'Xã Trần Văn Thời', 'id_quan_huyen' => 92],
    ['ten_phuong_xa' => 'Xã Cái Nước', 'id_quan_huyen' => 93],
    ['ten_phuong_xa' => 'Xã Hòa Mỹ', 'id_quan_huyen' => 93],
    ['ten_phuong_xa' => 'Xã Ngọc Hiển', 'id_quan_huyen' => 93],
    ['ten_phuong_xa' => 'Xã Năm Căn', 'id_quan_huyen' => 94],
    ['ten_phuong_xa' => 'Xã Tân Dân', 'id_quan_huyen' => 94],
    ['ten_phuong_xa' => 'Xã Hòa Bình', 'id_quan_huyen' => 94],
    ['ten_phuong_xa' => 'Xã Phú Tân', 'id_quan_huyen' => 95],
    ['ten_phuong_xa' => 'Xã Tân Thạnh', 'id_quan_huyen' => 95],
    ['ten_phuong_xa' => 'Xã Nguyễn Huệ', 'id_quan_huyen' => 95],
    ['ten_phuong_xa' => 'Xã Đầm Dơi', 'id_quan_huyen' => 96],
    ['ten_phuong_xa' => 'Xã Tân Thạnh', 'id_quan_huyen' => 96],
    ['ten_phuong_xa' => 'Xã Tân Lập', 'id_quan_huyen' => 96],
    ['ten_phuong_xa' => 'Phường Sông Bằng', 'id_quan_huyen' => 97],
    ['ten_phuong_xa' => 'Phường Đề Thám', 'id_quan_huyen' => 97],
    ['ten_phuong_xa' => 'Phường Hợp Giang', 'id_quan_huyen' => 97],
    ['ten_phuong_xa' => 'Xã Quang Hán', 'id_quan_huyen' => 98],
    ['ten_phuong_xa' => 'Xã Duy Quang', 'id_quan_huyen' => 98],
    ['ten_phuong_xa' => 'Xã Phúc Sen', 'id_quan_huyen' => 98],
    ['ten_phuong_xa' => 'Xã Bảo Lạc', 'id_quan_huyen' => 99],
    ['ten_phuong_xa' => 'Xã Xuân Hòa', 'id_quan_huyen' => 99],
    ['ten_phuong_xa' => 'Xã Bảo Lâm', 'id_quan_huyen' => 100],
    ['ten_phuong_xa' => 'Xã Phú Linh', 'id_quan_huyen' => 100],
    ['ten_phuong_xa' => 'Xã Hạ Lang', 'id_quan_huyen' => 101],
    ['ten_phuong_xa' => 'Xã Phú Hòa', 'id_quan_huyen' => 101],
    ['ten_phuong_xa' => 'Xã Lý Thông', 'id_quan_huyen' => 101],
    ['ten_phuong_xa' => 'Xã Hòa An', 'id_quan_huyen' => 102],
    ['ten_phuong_xa' => 'Xã Quảng Hòa', 'id_quan_huyen' => 102],
    ['ten_phuong_xa' => 'Xã Minh Khai', 'id_quan_huyen' => 102],
    ['ten_phuong_xa' => 'Xã Nguyên Bình', 'id_quan_huyen' => 103],
    ['ten_phuong_xa' => 'Xã Quảng Lâm', 'id_quan_huyen' => 103],
    ['ten_phuong_xa' => 'Xã Vĩnh Quang', 'id_quan_huyen' => 103],
    ['ten_phuong_xa' => 'Xã Quảng Uyên', 'id_quan_huyen' => 104],
    ['ten_phuong_xa' => 'Xã Hồng Quang', 'id_quan_huyen' => 104],
    ['ten_phuong_xa' => 'Xã Thạch An', 'id_quan_huyen' => 105],
    ['ten_phuong_xa' => 'Xã Phú Lâm', 'id_quan_huyen' => 105],
    ['ten_phuong_xa' => 'Phường Cái Răng', 'id_quan_huyen' => 106],
    ['ten_phuong_xa' => 'Phường Ba Láng', 'id_quan_huyen' => 106],
    ['ten_phuong_xa' => 'Phường Hưng Phú', 'id_quan_huyen' => 106],
    ['ten_phuong_xa' => 'Phường Ninh Kiều', 'id_quan_huyen' => 107],
    ['ten_phuong_xa' => 'Phường Cái Khế', 'id_quan_huyen' => 107],
    ['ten_phuong_xa' => 'Phường Tân An', 'id_quan_huyen' => 107],
    ['ten_phuong_xa' => 'Phường Bình Thủy', 'id_quan_huyen' => 108],
    ['ten_phuong_xa' => 'Phường Long Tuyền', 'id_quan_huyen' => 108],
    ['ten_phuong_xa' => 'Phường Bùi Hữu Nghĩa', 'id_quan_huyen' => 108],
    ['ten_phuong_xa' => 'Xã Phong Điền', 'id_quan_huyen' => 109],
    ['ten_phuong_xa' => 'Xã Tân Thới', 'id_quan_huyen' => 109],
    ['ten_phuong_xa' => 'Xã Mỹ Khánh', 'id_quan_huyen' => 109],
    ['ten_phuong_xa' => 'Xã Cờ Đỏ', 'id_quan_huyen' => 110],
    ['ten_phuong_xa' => 'Xã Thạnh An', 'id_quan_huyen' => 110],
    ['ten_phuong_xa' => 'Xã Trung An', 'id_quan_huyen' => 110],
    ['ten_phuong_xa' => 'Xã Vĩnh Thạnh', 'id_quan_huyen' => 111],
    ['ten_phuong_xa' => 'Xã Thạnh Lợi', 'id_quan_huyen' => 111],
    ['ten_phuong_xa' => 'Xã Thạnh Quới', 'id_quan_huyen' => 111],
    ['ten_phuong_xa' => 'Xã Thới Lai', 'id_quan_huyen' => 112],
    ['ten_phuong_xa' => 'Xã Tân Thới', 'id_quan_huyen' => 112],
    ['ten_phuong_xa' => 'Xã Đông Thạnh', 'id_quan_huyen' => 112],
    ['ten_phuong_xa' => 'Xã Kiên Bình', 'id_quan_huyen' => 113],
    ['ten_phuong_xa' => 'Xã Bình Thạnh', 'id_quan_huyen' => 113],
    ['ten_phuong_xa' => 'Xã Thạnh Hòa', 'id_quan_huyen' => 113],
    ['ten_phuong_xa' => 'Phường Thạch Thang', 'id_quan_huyen' => 114],
    ['ten_phuong_xa' => 'Phường Hải Châu I', 'id_quan_huyen' => 114],
    ['ten_phuong_xa' => 'Phường Hải Châu II', 'id_quan_huyen' => 114],
    ['ten_phuong_xa' => 'Phường Nam Dương', 'id_quan_huyen' => 114],
    ['ten_phuong_xa' => 'Phường Hòa Cường Bắc', 'id_quan_huyen' => 114],
    ['ten_phuong_xa' => 'Phường Hòa Cường Nam', 'id_quan_huyen' => 114],
    ['ten_phuong_xa' => 'Phường Phước Ninh', 'id_quan_huyen' => 114],
    ['ten_phuong_xa' => 'Phường Thanh Bình', 'id_quan_huyen' => 114],
    ['ten_phuong_xa' => 'Phường Chính Gián', 'id_quan_huyen' => 114],
    ['ten_phuong_xa' => 'Phường Thanh Khê Đông', 'id_quan_huyen' => 115],
    ['ten_phuong_xa' => 'Phường Thanh Khê Tây', 'id_quan_huyen' => 115],
    ['ten_phuong_xa' => 'Phường Xuân Hà', 'id_quan_huyen' => 115],
    ['ten_phuong_xa' => 'Phường An Khê', 'id_quan_huyen' => 115],
    ['ten_phuong_xa' => 'Phường Hòa Khê', 'id_quan_huyen' => 115],
    ['ten_phuong_xa' => 'Phường Vĩnh Trung', 'id_quan_huyen' => 115],
    ['ten_phuong_xa' => 'Phường Liên Chiểu', 'id_quan_huyen' => 116],
    ['ten_phuong_xa' => 'Phường Hòa Hiệp Bắc', 'id_quan_huyen' => 116],
    ['ten_phuong_xa' => 'Phường Hòa Hiệp Nam', 'id_quan_huyen' => 116],
    ['ten_phuong_xa' => 'Phường Lý Sơn', 'id_quan_huyen' => 116],
    ['ten_phuong_xa' => 'Phường Cẩm Lệ', 'id_quan_huyen' => 117],
    ['ten_phuong_xa' => 'Phường Hòa Thọ Tây', 'id_quan_huyen' => 117],
    ['ten_phuong_xa' => 'Phường Hòa Thọ Đông', 'id_quan_huyen' => 117],
    ['ten_phuong_xa' => 'Phường Hòa An', 'id_quan_huyen' => 117],
    ['ten_phuong_xa' => 'Phường Khuê Trung', 'id_quan_huyen' => 117],
    ['ten_phuong_xa' => 'Xã Hòa Sơn', 'id_quan_huyen' => 118],
    ['ten_phuong_xa' => 'Xã Hòa Phú', 'id_quan_huyen' => 118],
    ['ten_phuong_xa' => 'Xã Hòa Khương', 'id_quan_huyen' => 118],
    ['ten_phuong_xa' => 'Xã Hòa Ninh', 'id_quan_huyen' => 118],
    ['ten_phuong_xa' => 'Xã Hòa Tiến', 'id_quan_huyen' => 118],
    ['ten_phuong_xa' => 'Xã Hòa Châu', 'id_quan_huyen' => 118],
    ['ten_phuong_xa' => 'Xã Hòa Phước', 'id_quan_huyen' => 118],
    ['ten_phuong_xa' => 'Xã Hòa Quý', 'id_quan_huyen' => 118],
    ['ten_phuong_xa' => 'Thị trấn Hòa Vang', 'id_quan_huyen' => 118],
    ['ten_phuong_xa' => 'Phường Thọ Quang', 'id_quan_huyen' => 119],
    ['ten_phuong_xa' => 'Phường Mân Thái', 'id_quan_huyen' => 119],
    ['ten_phuong_xa' => 'Phường An Hải Đông', 'id_quan_huyen' => 119],
    ['ten_phuong_xa' => 'Phường An Hải Bắc', 'id_quan_huyen' => 119],
    ['ten_phuong_xa' => 'Phường Phước Mỹ', 'id_quan_huyen' => 119],
    ['ten_phuong_xa' => 'Phường Nại Hiên Đông', 'id_quan_huyen' => 119],
    ['ten_phuong_xa' => 'Phường Mỹ An', 'id_quan_huyen' => 120],
    ['ten_phuong_xa' => 'Phường Khuê Mỹ', 'id_quan_huyen' => 120],
    ['ten_phuong_xa' => 'Phường Hoà Quý', 'id_quan_huyen' => 120],
    ['ten_phuong_xa' => 'Phường Mỹ Khê', 'id_quan_huyen' => 120],
    ['ten_phuong_xa' => 'Phường Non Nước', 'id_quan_huyen' => 120],





































        ]);
    }
}
